language: cpp

sudo: false

compiler:
  - gcc

before_script:
  - autoreconf --force --install

script:
  - ./configure && make && make check; cat test/test-suite.log;

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"